name: Orebfuscator
main: com.lishid.orebfuscator.Orebfuscator
version: 1.6.2
author: lishid
softdepend: [Spout, ProtocolLib]
load: startup
description: >
             Modify chunk packets sent to players to prevent x-ray by replacing ores and other valuables.
commands:
  ofc:
    description: Manage Orebfuscator.
    usage: |
           /<command> [Command] [Arguments...]
           ==Commands==
           engine <1/2> - Set engine mode to 1 or 2
           initialradius [number] - Set block initial radius
           updateradius [number] - Set block update radius
           threads [number] - Set allowed processing threads
           proximity [number] - Set ProximityHider distance
           reload - Reload from config file
           status - Show status of Orebfuscator
           clearcache - Clear all cache
           enable/disable - Change the state of the plugin
           enable/disable world <worldname>
           enable/disable <Setting> - possible settings:
           (op, perms, updatethread, proximity, cache, axr, notification)
  rechunk:
    description: Re-send chunks.
    usage: |
           /<command> [radius=2] Send the chunks within a specific radius